name: NexusBill Auto Sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Sync Endpoint
        run: curl -s "https://www.rdnisp.com/api/cron/sync-enforcer?secret=isp-cron-secret-2024"
